### ISSUE TITLE
WHAT on subclass fails

### ISSUE THREAD

**Issue by wayland** [lizmat/Hash-Ordered#7]
## Problem

The following code crashes but shouldn't:
```
raku -e 'use Hash::Ordered; class A does Hash::Ordered { method f() {} }; say A.WHAT'
```

## Context

I've submitted a PR that has a test for this problem.  Feel free to adjust as appropriate.  

Thanks!

**Comment by lizmat** [comment]
Thanks for the report.  The problem was actually deeper and also affected `.Str` and `.raku`, apart from `.gist`.

Fixed in release [0.0.7](https://raku.land/zef:lizmat/Hash::Ordered)
